name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SwiftFormat
        run: brew install swiftformat

      - name: Run SwiftFormat in Strict Mode
        run: swiftformat . --strict
